### ISSUE TITLE
Veuillez documenter les variables. / Please document the variables.

### ISSUE THREAD

**Issue by Poikilos** [ElMoribond/screenrulerzoom#1]
translate.google.com:
- J'essaie d'améliorer le logiciel en ajoutant un réglage DPI sous-pixel, mais la signification de chaque variable courte est très difficile à comprendre.
- Veuillez fournir une explication dans les commentaires en anglais ou en français dans le code lorsque les variables sont déclarées, en particulier de oH, cUM, cpt et autres dans paintEvent.

Autres problèmes de lisibilité :
- Notez également que min et max sont des mots réservés en Python (et mis en évidence en tant que fonctions intégrées dans les éditeurs Python), veuillez donc les remplacer par "premier" et "dernier".
- Le code est plus lisible avec PEP8, pensez donc à placer des espaces de chaque côté d'un opérateur binaire lorsqu'il ne fait pas partie d'un paramètre ([PEP8 id28](https://www.python.org/dev/peps/pep-0008/ #id28)) 

/

- I am trying to improve the software by adding a sub-pixel DPI adjustment, but the meaning of each short variable is very difficult to understand.
- Please provide an explanation in English or French comments within the code when the variables are declared, especially of oH, cUM, cpt, and others in paintEvent.

Other readability issues:
- Also note that min and max are reserved words in Python (and highlighted as builtin functions in Python editors), so please change them to `first` and `last`.
- The code is more readable using PEP8, so consider placing spaces on each side of a binary operator when not part of a parameter ([PEP8 id28](https://www.python.org/dev/peps/pep-0008/#id28))

**Comment by ElMoribond** [comment]
Bonjour,

Vous avez raison le code n'est pas très lisible.

Je suis désolé de ne pouvoir satisfaire votre demande.
Je n'ai plus l'environnement adéquat et pas le temps d'y remédier.

Cependant, vous pouvez trouver la signification de ces variables aux lignes 141 et 153.
C'est probablement la seconde raison pour laquelle j'ai utilisé des noms aussi courts.

La variable locale cpt est un compteur, j'aurais dû la nommer cnt ou count/counter.
Utilisée avec str dans drawText j'en déduis que c'est un chiffre utilisé en string.
Donc de très forte chance que ce soit le chiffre affiché sur la règle.
Essayez str(cpt) + "_" dans les drawText pour confirmer.

**Comment by Poikilos** [comment]
Merci d'avoir répondu. Les informations que vous fournissez m'aideront à progresser.  / Thank you for responding. The information you provided will help me progress. 

Pour référence, voici la traduction ainsi que les permaliens vers ces lignes : / For reference, here is the translation along with permalinks to those lines:

> Hello,
> 
> You are right the code is not very readable.
> 
> I am sorry that I cannot meet your request.
> I no longer have the right environment and no time to fix it.
> 
> However, you can find the meaning of these variables on lines [141](https://github.com/ElMoribond/screenrulerzoom/blob/6c99dc22f39c8fe30b17cdc3b804fe66f414aac0/screenrulerzoom.py#L141) and [153](https://github.com/ElMoribond/screenrulerzoom/blob/6c99dc22f39c8fe30b17cdc3b804fe66f414aac0/screenrulerzoom.py#L153).
> This is probably the second reason I used such short names.
> 
> The local variable cpt is a counter, I should have named it cnt or count / counter.
> Used with str in drawText I deduce that it is a number used in string.
> So very likely that this is the number displayed on the ruler.
> Try str (cpt) + "_" in the drawText to confirm.

**Comment by poikilos** [comment]
Quel éditeur as-tu utilisé ? Je veux pouvoir éditer les fichiers po et pot et compiler le fichier mo.  / What editor did you use? I want to be able to edit the po and pot files and compile the mo file.

**Comment by Poikilos** [comment]
Ceci est résolu dans <https://github.com/poikilos/screenrulerzoom/commit/eaf3a01f3f0e794c8a5a28cd70615db98d6478fa> dans mon fork. J'aurai apparemment la suite maintenue du programme. 
/
This is resolved in <https://github.com/poikilos/screenrulerzoom/commit/eaf3a01f3f0e794c8a5a28cd70615db98d6478fa> in my fork. I will apparently have the maintained continuation of the program.
