### ISSUE TITLE
Quel logiciel avez-vous utilisé pour éditer les fichiers sources de la traduction ? 

### ISSUE THREAD

**Issue by Poikilos** [ElMoribond/screenrulerzoom#2]
Quel éditeur as-tu utilisé ? Je veux pouvoir éditer les fichiers po et pot et compiler le fichier mo.  / What editor did you use? I want to be able to edit the po and pot files and compile the mo file.

**Comment by ElMoribond** [comment]
Aucun, seulement la commande gettext.

**Comment by Poikilos** [comment]
> Aucun, seulement la commande gettext.

translate.google.com: "None, just the gettext command."

-ElMoribond

OK, je comprends que vous utilisez uniquement une interface de ligne de commande. J'utiliserai POEdit ou quelque chose si je veux une interface graphique, je peux compiler le fichier mo à l'aide de commandes (https://stackoverflow.com/a/18019221/4541104).

Merci.
/
OK, I understand you are only using a command-line interface. I'll use POEdit or something if I want a GUI then I can compile the mo file using commands (https://stackoverflow.com/a/18019221/4541104).

Thank you.
